### ISSUE TITLE
download voxceleb

### ISSUE THREAD

**Issue by guanjian729** [cyrta/voxceleb#1]
hello，i am a student and i  have a queastion.   i can download dataset with this commond : ./download.sh list.txt     but all download audio is in a file.   how should I do to divide the dataset into speaker ?or how to run your code? very thank.

**Comment by cyrta** [comment]
This is work in progress, It is not usable right now.

**Comment by guanjian729** [comment]
ok,very thanks.

**Comment by 22w2w2** [comment]
Will the problem be solved now? Thank you
